### ISSUE TITLE
How to add a unique shader to a single V3DObject?

### ISSUE THREAD

**Issue by OwlHowlinMornSky** [gamepopper/Vigilante-Game-Framework#3]
I'm using this libary for 3D game, and I'd like to add some shader to characters but the whole scene.
Are there some functions that allows me to do this? Or there are workarounds.

**Comment by gamepopper** [comment]
Hello, sorry for the late response. I don't think this is possible currently, but I now have some free time that I can implement something.

**Comment by gamepopper** [comment]
Just pushed a new property for V3DObject: OverrideShader.

By default, this property will be NULL. However, if you set up and set it to a V3DShader object, the scene will use OverrideShader instead of whatever shader is defined for the V3DScene.

From V3DScene::RenderGroup(VGroup* group) in V3DScene.cpp:
```
if (base != nullptr)
{
	if (base->OverrideShader != nullptr)
		base->UpdateShader(base->OverrideShader, Camera[CurrentCamera].get());
	else
		base->UpdateShader(Shader.get(), Camera[CurrentCamera].get());

	if (Camera[CurrentCamera]->BoxInView(base->Position, base->GetMinimum(), base->GetMaximum()) && base->exists && base->visible)
	{
		base->Draw(renderTex); //If Renderable 3D Object
	}
}
```

See if this will do what you are trying to do.

If not, you should be able to override the UpdateShader function in V3DObject and any class that inherits from it.

**Comment by OwlHowlinMornSky** [comment]
OK. It works. Thanks!
In fact, I've add 
> 
	shader->Update();
	shader->Bind();
in the beginning of V3DModel::UpdateShader().
But because the shader of V3DScene is binded in V3DScene::GetTexture(), the above change breaks it.
So there is a lot of things should be rewritten...

( If those shder-overrided models are last Add()ed, the program looks having no problem, anyway.
